application:
  input:
    file:
      contentType: "application/x-yaml,text/yaml,application/octet-stream',text/x-java-properties,text/plain"
      contentType-yaml: "application/x-yaml,text/yaml"
      contentType-prop: "text/x-java-properties"
  output:
    defaultFileName: "secure-properties"
  process:
    tempFileName: "tempInputPropFile"