#%RAML 1.0
title: Secure Mule Properties API
baseUri: http://localhost:8081/api
version: 1.0.0
protocols:
  - HTTP
  - HTTPS
description: "The API makes use of **Secure Properties Tool** jar file available from mulesoft.com to facilitate encryption/decryption of strings, property values or complete property file contents for a MuleSoft project via web service. This service supports both, **.yaml** and **.properties** files."

/string:
  post:
    displayName: Encrypt Text Strings
    description: Encrypts a single text string provided as parameter <value>
    body:
      multipart/form-data:
        description: Required parameters for encryption or decryption operation
        properties:
          operation:
            description: Sets the operation to perform.
            default: encrypt
            enum:
              - encrypt
              - decrypt
            type: string
          algorithm:
            description: Specifies the algorithm to use during the operation.
            default: AES
            enum:
              - AES
              - Blowfish
              - DES
              - DESede
              - RC2
              - RCA
            type: string
          mode:
            description: Specifies the mode to use during the operation.
            default: CBC
            enum:
              - CBC
              - CFB
              - ECB
              - OFB
            type: string
          key:
            description: Specifies the word used to lock or unlock the file or value during the operation.
            example: mulesoft01234567
            type: string
          value:
            description: Specifies the string value that is encrypted or decrypted during the 'string' operation.
            example: random string to encrypt
            type: string
    responses:
      "200":
        description: Encrypted / decrypted string returned in JSON format
        body:
          application/json:
            properties:
              output:
                example: 8q5e1+jy0cND2iV2WPThahmz6XsDwB6Z
                type: string
      "400":
        body:
          application/json:
            properties:
              message:
                example: Bad request
                type: string
      "405":
        body:
          application/json:
            properties:
              message:
                example: Method not allowed
                type: string
      "406":
        body:
          application/json:
            properties:
              message:
                example: Not acceptable
                type: string
      "415":
        body:
          application/json:
            properties:
              message:
                example: Unsupported media type
                type: string
      "501":
        body:
          application/json:
            properties:
              message:
                example: Not Implemented
                type: string
      "500":
        body:
          application/json:
            properties:
              message:
                example: Unknown error occurred while processing request
                type: string

/file:
  post:
    displayName: Encrypt Properties Inside a File
    description: Encrypts the value of each property set in the properties file provided as parameter **\<input-file\>**.
    body:
      multipart/form-data:
        description: Required parameters for encryption or decryption operation
        properties:
          operation:
            description: Sets the operation to perform.
            default: encrypt
            enum:
              - encrypt
              - decrypt
            type: string
          algorithm:
            description: Specifies the algorithm to use during the operation.
            default: AES
            enum:
              - AES
              - Blowfish
              - DES
              - DESede
              - RC2
              - RCA
            type: string
          mode:
            description: Specifies the mode to use during the operation.
            default: CBC
            enum:
              - CBC
              - CFB
              - ECB
              - OFB
            type: string
          key:
            description: Specifies the word used to lock or unlock the file or value during the operation.
            example: mulesoft01234567
            type: string          
          input-file:
            description: Specifies the properties file that is encrypted or decrypted during the **file** or **file-level** operation.
            fileTypes:
              - application/x-yaml
              - text/yaml
              - text/plain
              - text/x-java-properties              
              - application/octet-stream
          output-file-name:
            description: Specifies the name of the encrypted or decrypted properties file (without extension) that is created after the **file** or **file-level** operation.
            default: secure-properties
            example: secure-properties
            type: string
    responses:
      "200":
        description: Retrieved encrypted / decrypted file
        body:
          "*/*":
            type: object
      "400":
        body:
          application/json:
            properties:
              message:
                example: Bad request
                type: string
      "405":
        body:
          application/json:
            properties:
              message:
                example: Method not allowed
                type: string
      "406":
        body:
          application/json:
            properties:
              message:
                example: Not acceptable
                type: string
      "415":
        body:
          application/json:
            properties:
              message:
                example: Unsupported media type
                type: string
      "501":
        body:
          application/json:
            properties:
              message:
                example: Not Implemented
                type: string
      "500":
        body:
          application/json:
            properties:
              message:
                example: Unknown error occurred while processing request
                type: string

/file-level:
  post:
    displayName: Encrypt All the Content of a File
    description: Encrypts all the content of the properties file provided as parameter **\<input-file\>**
    body:
      multipart/form-data:
        description: Required parameters for encryption or decryption operation
        properties:
          operation:
            description: Sets the operation to perform.
            default: encrypt
            enum:
              - encrypt
              - decrypt
            type: string
          algorithm:
            description: Specifies the algorithm to use during the operation.
            default: AES
            enum:
              - AES
              - Blowfish
              - DES
              - DESede
              - RC2
              - RCA
            type: string
          mode:
            description: Specifies the mode to use during the operation.
            default: CBC
            enum:
              - CBC
              - CFB
              - ECB
              - OFB
            type: string
          key:
            description: Specifies the word used to lock or unlock the file or value during the operation.
            example: mulesoft01234567
            type: string          
          input-file:
            description: Specifies the properties file that is encrypted or decrypted during the **file** or **file-level** operation.
            fileTypes:
              - application/x-yaml
              - text/yaml
              - text/plain
              - text/x-java-properties
              - application/octet-stream
          output-file-name:
            description: Specifies the name of the encrypted or decrypted properties file (without extension) that is created after the **file** or **file-level** operation.
            default: secure-properties
            example: secure-properties
            type: string
    responses:
      "200":
        description: Retrieved encrypted / decrypted file
        body:
          "*/*":
            type: object
      "400":
        body:
          application/json:
            properties:
              message:
                example: Bad request
                type: string
      "405":
        body:
          application/json:
            properties:
              message:
                example: Method not allowed
                type: string
      "406":
        body:
          application/json:
            properties:
              message:
                example: Not acceptable
                type: string
      "415":
        body:
          application/json:
            properties:
              message:
                example: Unsupported media type
                type: string
      "501":
        body:
          application/json:
            properties:
              message:
                example: Not Implemented
                type: string
      "500":
        body:
          application/json:
            properties:
              message:
                example: Unknown error occurred while processing request
                type: string
